# You may configure 1 or more twines.
# The 'twine_name' is the colloquial name for your twine.
# To get your 'twine_id', go to https://twine.cc and select the twine. The URL should contain your twine ID.
# The access key for the twine can be found within the html code under 'Share'.
twines:
  first_twine:
    twine_name: "twine_name"
    twine_id: twine_id
    twine_access_key: twine_access_key
  second_twine:
    twine_name: "twine_name"
    twine_id: twine_id
    twine_access_key: twine_access_key
  third_twine:
    twine_name: "twine_name"
    twine_id: twine_id
    twine_access_key: twine_access_key

# Your local weather is determined by accessing the Yahoo! weather API with your WOEID.
# This is a geographical ID, which you can lookup at http://woeid.factormystic.net/.
woeid: your_woeid

# In order to use the Google Drive API, we must autheticate.
# The spreadhseet key can be found in the URL of the spreadsheet as the key variable.
google_username: google_username
google_password: google_password
google_spreadsheet_key: spreadsheet_key
