twine_id: twine_id
twine_access_key: twine_access_key
woeid: your_postal_code_check_out_http://woeid.factormystic.net/_to_find_yours
google_username: google_username
google_password: google_password
google_spreadsheet_key: spreadsheet_key_can_be_found_in_the_url_of_the_spreadsheet